spring:
  datasource:
    url: jdbc:h2:mem:bfhdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

bfh:
  participant:
    name: "Aryan Kumar"
    regNo: "22BCE0235"
    email: "aryan.kumar2022a@vitstudent.ac.in"
  endpoints:
    generateWebhook: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"
    fallbackSubmit: "https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA"
  http:
    # Some gateways require 'Bearer <token>' while the PDF shows plain token.
    # Options: PLAIN or BEARER
    authScheme: "PLAIN"
